<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYHI9jhr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYHI9jhr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYHI9jhr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYHI9jhr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYHI9jhr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YHI9jhr',
    'container.build_id' => 'fbc335b0',
    'container.build_time' => 1676194050,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYHI9jhr');
